# PS-WRAP: สร้าง glyph ปุ่มจอย (buttons-ps.svg, l1/r1/l3/r3.svg) — รันซ้ำได้: python scripts/gen-glyphs.py
# สไตล์: แผ่นเข้ม gradient + ขอบบาง · face buttons สีแบบ PS · L/R ตัวอักษรสว่าง
# ตัวอักษร L1/R1/L3/R3 ดึง path จาก upstream เดิม (โฟลเดอร์ scripts/glyph-src/)
import re, pathlib
ROOT = pathlib.Path(__file__).resolve().parent
RES = ROOT.parent / "chiaki-ng" / "gui" / "res"
SRC = ROOT / "glyph-src"

TOP, BOTTOM = "#3c4a5e", "#1d2631"   # gradient ของแผ่น
RING = 'stroke="#ffffff" stroke-opacity="0.24"'
LABEL = "#e8edf2"                     # Theme.text
COLORS = {"cross": "#7fa8ff", "moon": "#ff6b81", "box": "#f08bd6", "pyramid": "#3fdcae"}

def grad(gid, y0, y1):
    return (f'<linearGradient id="{gid}" gradientUnits="userSpaceOnUse" x1="0" y1="{y0}" x2="0" y2="{y1}">'
            f'<stop offset="0" stop-color="{TOP}"/><stop offset="1" stop-color="{BOTTOM}"/></linearGradient>')

def letters(name, first_abs):
    d = re.search(r'\sd="([^"]+)"', (SRC / f"{name}.svg").read_text()).group(1)
    idx = re.search(r'[zZ]\s+[mM]', d).end() - 1      # ทิ้ง outline เดิม (ล้น viewBox) เก็บแต่ตัวอักษร
    rest = d[idx:]
    return re.sub(r'^[mM]\s*[-\d.]+[ ,][-\d.]+', f"M {first_abs[0]},{first_abs[1]}", rest)

def write(name, shape, letter_d, center):
    dx, dy = 128 - center[0], 128 - center[1]
    svg = f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- PS-WRAP: generated by scripts/gen-glyphs.py -->
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="256" height="256" viewBox="0 0 256 256">
  <defs>{grad("g", 0, 256)}</defs>
  {shape}
  <path fill="{LABEL}" fill-rule="evenodd" transform="translate({dx:.3f},{dy:.3f})" d="{letter_d}" />
</svg>
'''
    (RES / f"{name}.svg").write_text(svg, encoding="utf-8")

PILL = f'<rect x="10" y="46" width="236" height="164" rx="50" fill="url(#g)" {RING} stroke-width="7" />'
DISC = f'<circle cx="128" cy="128" r="122" fill="url(#g)" {RING} stroke-width="7" />'

write("l1", PILL, letters("l1", (96.048828, 111.22656)), (149.4, 149.96))
write("r1", PILL, letters("r1", (46.933594, 111.22656)), (107.3, 149.96))
write("l3", DISC, letters("l3", (127.02734, 118.39453)), (99.8, 157.8))
write("r3", DISC, letters("r3", (190.10352, 118.39453)), (155.6, 157.8))

# face buttons sprite — QmlSvgProvider วาด "circle" แล้ววาด glyph ทับ (มี element "styled" = ไม่เจาะ)
V = 135.46666
C = V / 2
def st(k): return f'fill="none" stroke="{COLORS[k]}" stroke-width="9.5" stroke-linecap="round" stroke-linejoin="round"'
a, box, side = 21, 21, 54
h = side * 3 ** 0.5 / 2; ty = C + 2.5
(RES / "buttons-ps.svg").write_text(f'''<?xml version="1.0" encoding="UTF-8"?>
<!-- PS-WRAP: generated by scripts/gen-glyphs.py -->
<svg xmlns="http://www.w3.org/2000/svg" version="1.1" width="512" height="512" viewBox="0 0 {V} {V}">
  <defs>{grad("g", 0, V)}</defs>
  <g id="styled">
    <g id="circle">
      <rect x="0" y="0" width="{V}" height="{V}" fill="none" />
      <circle cx="{C:.4f}" cy="{C:.4f}" r="{C-2:.4f}" fill="url(#g)" {RING} stroke-width="3.5" />
    </g>
    <rect id="box" x="{C-box:.4f}" y="{C-box:.4f}" width="{2*box}" height="{2*box}" rx="3" {st("box")} />
    <circle id="moon" cx="{C:.4f}" cy="{C:.4f}" r="23" {st("moon")} />
    <path id="pyramid" d="M {C:.4f},{ty-h*2/3:.4f} L {C+side/2:.4f},{ty+h/3:.4f} L {C-side/2:.4f},{ty+h/3:.4f} Z" {st("pyramid")} />
    <path id="cross" d="M {C-a:.4f},{C-a:.4f} L {C+a:.4f},{C+a:.4f} M {C+a:.4f},{C-a:.4f} L {C-a:.4f},{C+a:.4f}" {st("cross")} />
  </g>
</svg>
''', encoding="utf-8")
print("ok")
